# Generated by Django 4.1.7 on 2023-05-31 07:02

import GreenLine.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('GreenLine', '0001_initial'), ('GreenLine', '0002_pdf'), ('GreenLine', '0003_rename_name_organization_organization'), ('GreenLine', '0004_rename_organization_organization_name'), ('GreenLine', '0005_rename_pdf_file'), ('GreenLine', '0006_remove_employee_mail_employee_phone'), ('GreenLine', '0007_alter_employee_kana_alter_employee_password_and_more'), ('GreenLine', '0008_alter_employee_kana'), ('GreenLine', '0009_city_prefecture_shipper_alter_employee_kana_and_more'), ('GreenLine', '0010_organization_kana_alter_organization_name'), ('GreenLine', '0011_consignee_prefecture'), ('GreenLine', '0012_remove_consignee_prefecture'), ('GreenLine', '0013_consignee_phone'), ('GreenLine', '0014_remove_file_phone'), ('GreenLine', '0015_alter_city_code_alter_consignee_city_town_and_more'), ('GreenLine', '0016_alter_town_detail'), ('GreenLine', '0017_remove_consignee_city_remove_town_detail_and_more')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('kana', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenLine.organization')),
                ('name', models.CharField(default='', max_length=32)),
                ('kana', models.CharField(default='', max_length=64, validators=[django.core.validators.RegexValidator(message='カナはカタカナのみ入力できます', regex='^[ァ-ヴー]+$')])),
                ('phone', models.CharField(default='', max_length=16, validators=[django.core.validators.RegexValidator(message='電話番号は半角数字のみ入力できます', regex='^[0-9]+$')])),
                ('password', models.CharField(default='', max_length=16)),
                ('auth', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=8)),
                ('kana', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=5, unique=True)),
                ('name', models.CharField(default='', max_length=32)),
                ('kana', models.CharField(default='', max_length=64)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenLine.prefecture')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=16, unique=True)),
                ('zip', models.CharField(default='', max_length=7)),
                ('name', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('kana', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenLine.city', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('kana', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('kana', models.CharField(default='', max_length=1024)),
                ('phone', models.CharField(default='', max_length=16)),
                ('town', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='GreenLine.town', to_field='code')),
                ('address', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('shipper', models.ManyToManyField(to='GreenLine.shipper')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GreenLine.consignee')),
                ('file', models.FileField(upload_to=GreenLine.models.upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
