# Generated by Django 4.0.6 on 2023-02-08 12:35

import GreenLine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenLine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=200)),
                ('file', models.FileField(upload_to=GreenLine.models.upload_path)),
            ],
        ),
    ]
