# Generated by Django 4.0.6 on 2023-02-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenLine', '0002_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='name',
            new_name='organization',
        ),
    ]
