# Generated by Django 4.0.6 on 2023-02-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenLine', '0003_rename_name_organization_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization',
            new_name='name',
        ),
    ]
