# Generated by Django 4.0.6 on 2023-02-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenLine', '0004_rename_organization_organization_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pdf',
            new_name='File',
        ),
    ]
