# Generated by Django 4.0.3 on 2023-02-27 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenLine', '0005_rename_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='mail',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(message='電話番号は半角数字のみ入力できます', regex='^[0-9]+$')]),
        ),
    ]
