# Generated by Django 4.0.6 on 2023-03-01 14:52

import GreenLine.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenLine', '0006_remove_employee_mail_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='kana',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(message='カナはカタカナのみ入力できます', regex='^[ァ-ヴ]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=GreenLine.models.upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
