# Generated by Django 4.1.7 on 2023-03-17 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenLine', '0007_alter_employee_kana_alter_employee_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='kana',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(message='カナはカタカナのみ入力できます', regex='^[ァ-ヴー]+$')]),
        ),
    ]
