# Generated by Django 4.1.7 on 2023-04-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenLine', '0009_city_prefecture_shipper_alter_employee_kana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='kana',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
