# Generated by Django 4.1.7 on 2023-04-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenLine', '0012_remove_consignee_prefecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignee',
            name='phone',
            field=models.CharField(default='', max_length=16),
        ),
    ]
