# Generated by Django 4.1.7 on 2023-04-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenLine', '0013_consignee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='phone',
        ),
    ]
